### PR TITLE
Script for writing RDSSpy compatible sample files

### PR DESCRIPTION
**Pull request by andimik**
rtl-rx_rdsspy.sh will write PI-Code, Date, Time and Frequency to the file name in the current directory

### CODE REVIEW

**Comment by windytan** [comment]
I've added this command in the [wiki][Wiki: Usage] instead.

[Wiki: Usage]: https://github.com/windytan/redsea/wiki/Use-cases

**Comment by andimik** [comment]
Ok

**Comment by andimik** [comment]
One question: I wanted to improve it by adding the timestamp (like in the original RDSSPY app), 

```
<recorder="RDS Spy" date="2020-01-07" time="18-39-02" source="2" name="" location="" notes="">
A3DD 0403 E376 4120 @2020/01/07 18:39:00.86
A3DD 0400 767F 522E @2020/01/07 18:39:00.86
A3DD 0401 E376 4D41 @2020/01/07 18:39:00.94
A3DD 0402 767F 5249 @2020/01/07 18:39:01.01
A3DD 0403 E376 4120 @2020/01/07 18:39:01.21
A3DD 0400 767F 522E @2020/01/07 18:39:01.21
```


but microseconds are not detected with parameter `%f`

```
#!/bin/sh
rtl_fm -M fm -l 0 -A std -p 0 -s 171k -g 40 -F 9 $@ | redsea -x -t '@%Y/%m/%d %H:%M:%S.%f' | tee `head -12l | tail -1l | cut -d" " -f1`_`date +%F`_`date +%k`-`date +%M`-`date +%S`_$2Hz.spy
```

```
A203 0548 6C78 2020 @2020/05/13 20:28:31.%f
A203 2542 6575 6674 @2020/05/13 20:28:31.%f
A203 0549 E36F 4F45 @2020/05/13 20:28:31.%f
A203 2543 2059 6F75 @2020/05/13 20:28:31.%f
A203 E545 7B22 A201 @2020/05/13 20:28:31.%f
A203 054A 6F78 2033 @2020/05/13 20:28:31.%f
A203 2544 2053 686F @2020/05/13 20:28:31.%f
```

Do you have an idea?

**Comment by windytan** [comment]
Unlike Python's `datetime.now().strftime()`, the C `strftime` used by redsea doesn't support fractional seconds. A possible solution would be to add a special option just for printing the timestamp in the RDS Spy format (`-T` or something); just thinking aloud.

**Comment by windytan** [comment]
This is an interesting problem and I want to do it right, I wrote some technical notes in #70 - mainly for myself but comments are welcome, too.

**Comment by windytan** [comment]
You should now be able to use "%f".

**Pull request closed without merging**
